java:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - 3.0
build:
  - type: maven
    version: 3.2.5
    goals: clean compile test --fail-never -Plong
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      ccm.java.home=$CCM_JAVA_HOME
      cassandra.version=$CCM_CASSANDRA_VERSION
      cassandra.branch="github:iamaleksey/10365"
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
